# -*- coding: utf-8 -*-
# Three additional audit checklists — D-0507 Flight Training
# VEN = Vendor / Contracted Service Provider Audit (D-0507-VAC-001) — single status
# SAF = School-wide Safety Audit (D-0507-SAC-001, ref OMM/TM/OMA) — dual Documented/Implemented
# SUR = Safety Surveillance of Activities (D-0507-SSC-001, ref FSOP/MMSOP) — single status
# item keys: d (EN), th (Thai), rk, mt (methods), how, ref, chk (optional sub-checklist)

VEN_PARTS = [
("V1 – Contract, Approvals & Insurance", "สัญญา การรับรอง และประกันภัย", [
 ("V1.1","Contract status / สถานะสัญญา",[
  dict(d="A written contract/SLA exists, is current, and its scope matches the services actually being provided to the ATO.",
      th="มีสัญญา/ข้อตกลงเป็นลายลักษณ์อักษร ยังมีผล และขอบเขตตรงกับบริการที่ให้จริง",
      rk="ORA.GEN.205", mt=["DOC","XCK"], ref="OMM contracted activities list",
      how="Sight the contract, check expiry and scope clauses vs actual services observed/invoiced in the last 3 months.",
      chk=["สัญญายังไม่หมดอายุ","ขอบเขตบริการตรงกับที่ใช้จริง","เงื่อนไขคุณภาพ/ความปลอดภัยระบุไว้","สิทธิของ ATO/กพท. ในการเข้าตรวจระบุไว้"]),
  dict(d="The vendor holds all certificates/approvals required for the service (e.g. AMO approval, fuel supplier authorisation, aerodrome licence, exam/medical provider approval) and they are current.",
      th="ผู้ให้บริการมีใบรับรอง/การอนุมัติที่จำเป็นครบและยังไม่หมดอายุ (เช่น AMO approval, ใบอนุญาตสนามบิน, การรับรองผู้ให้บริการสอบ/แพทย์)",
      rk="ORA.GEN.205", mt=["DOC"], ref="Vendor certificates file",
      how="List every approval the service legally requires, sight each certificate, record numbers + expiry dates."),
  dict(d="Vendor liability insurance is valid and adequate for the service provided.",
      th="ประกันภัยความรับผิดของผู้ให้บริการยังมีผลและวงเงินเพียงพอ",
      rk="ORA.GEN.205", mt=["DOC"], ref="Insurance certificate"),
  dict(d="Any subcontracting by the vendor is disclosed and acceptable to the ATO.",
      th="การจ้างช่วงต่อ (ถ้ามี) ได้แจ้งให้ ATO ทราบและยอมรับได้",
      rk="ORA.GEN.205", mt=["DOC","INT"], ref="Contract subcontracting clause"),
 ]),
]),
("V2 – Organisation & Personnel Competence", "องค์กรและความสามารถของบุคลากร", [
 ("V2.1","Personnel / บุคลากรผู้ให้บริการ",[
  dict(d="Personnel performing the service hold the required licences/qualifications; records sighted (e.g. maintenance personnel licences, fuel handler training, instructor/examiner approvals).",
      th="บุคลากรที่ปฏิบัติงานมีใบอนุญาต/คุณสมบัติตามที่กำหนด และตรวจเห็นบันทึกจริง",
      rk="ORA.GEN.205", mt=["DOC"], ref="Vendor personnel files",
      how="Sample the personnel who actually served the ATO in the last month (from work orders/delivery notes), verify their qualifications."),
  dict(d="Recurrent/refresher training of vendor personnel is current where required (e.g. dangerous goods, fuel quality control, human factors for AMO staff).",
      th="การอบรมทบทวนของบุคลากรผู้ให้บริการเป็นปัจจุบันตามที่กำหนด",
      rk="ORA.GEN.205", mt=["DOC"]),
  dict(d="Staffing level is adequate for the service demand; a named contact and escalation route for the ATO exists.",
      th="อัตรากำลังเพียงพอต่อปริมาณงาน มีผู้ประสานงานหลักและช่องทางยกระดับปัญหา",
      rk="ORA.GEN.205", mt=["INT"]),
 ]),
]),
("V3 – Facilities & Equipment", "สถานที่และอุปกรณ์ของผู้ให้บริการ", [
 ("V3.1","Facilities & equipment / สิ่งอำนวยความสะดวก",[
  dict(d="Facilities and equipment used for the service are adequate, serviceable and maintained (storage tanks, workshop, test equipment, classrooms as applicable).",
      th="สถานที่และอุปกรณ์เพียงพอ ใช้งานได้ และได้รับการบำรุงรักษา",
      rk="ORA.GEN.205", mt=["OBS"],
      how="Walk-through inspection with photos. For AMO: workshop condition, parts storage segregation (serviceable/unserviceable)."),
  dict(d="Measuring/test equipment is calibrated and within calibration due dates (torque wrenches, fuel test kits, pressure gauges).",
      th="เครื่องมือวัด/ทดสอบผ่านการสอบเทียบและยังไม่เกินกำหนด",
      rk="ORA.GEN.205", mt=["DOC","OBS"],
      how="Sample 3 items of calibrated equipment: check calibration stickers vs calibration records."),
  dict(d="Safety equipment at vendor facility is serviceable (fire extinguishers in date, spill kits, PPE available and used).",
      th="อุปกรณ์ความปลอดภัย ณ สถานที่ผู้ให้บริการพร้อมใช้ (ถังดับเพลิง, ชุดจัดการหกรั่วไหล, PPE)",
      rk="ORA.GEN.205", mt=["OBS"]),
 ]),
]),
("V4 – Service Delivery by Type", "การส่งมอบบริการตามประเภท (ข้ามส่วนที่ไม่เกี่ยวข้อง = N/A)", [
 ("V4.1","Fuel services / บริการเชื้อเพลิง (If applicable)",[
  dict(d="Fuel grade supplied is correct for the fleet; storage and dispensing quality control performed and recorded (daily water checks, filter checks, sampling).",
      th="เกรดเชื้อเพลิงถูกต้องกับฝูงบิน มีการควบคุมคุณภาพการจัดเก็บ/จ่าย และบันทึกจริง (ตรวจน้ำประจำวัน ตรวจไส้กรอง เก็บตัวอย่าง)",
      rk="ORA.GEN.205", mt=["DOC","OBS"], ref="Fuel QC log",
      chk=["บันทึกตรวจน้ำประจำวันครบ (สุ่ม 30 วัน)","บันทึกตรวจ/เปลี่ยนไส้กรอง","ป้ายระบุเกรดชัดเจน","อุปกรณ์ bonding ใช้งานได้"]),
  dict(d="Refuelling practice observed complies with fire precautions: bonding, extinguisher positioned, no occupants during fuelling, spill procedure known.",
      th="การเติมเชื้อเพลิงที่สังเกตเป็นไปตามข้อควรระวังอัคคีภัย",
      rk="ORA.GEN.205", mt=["OBS","INT"]),
  dict(d="Fuel uplift documentation is accurate and traceable to aircraft and payment records.",
      th="เอกสารการเติมเชื้อเพลิงถูกต้อง ตรวจสอบย้อนถึงอากาศยานและบันทึกการชำระได้",
      rk="ORA.GEN.205", mt=["XCK"]),
 ]),
 ("V4.2","Maintenance / AMO (If applicable)",[
  dict(d="Work is performed under work orders using current approved maintenance data; CRS issued by authorised certifying staff after each maintenance event.",
      th="งานซ่อมทำตาม work order โดยใช้ maintenance data ฉบับปัจจุบัน และออก CRS โดยผู้มีอำนาจทุกครั้ง",
      rk="ORA.GEN.205", mt=["DOC","XCK"], ref="MMSOP Work Order / AMO procedures",
      chk=["Work order เปิดครบทุกงาน (สุ่ม 5 งาน)","Maintenance data revision ปัจจุบัน","CRS ลงนามโดยผู้มีอำนาจ","ชั่วโมง/รอบเครื่องบันทึกถูกต้อง"]),
  dict(d="Parts and materials are traceable (release certificates / batch numbers); unserviceable parts segregated and tagged.",
      th="อะไหล่/วัสดุตรวจสอบย้อนได้ (ใบรับรอง/หมายเลข batch) ชิ้นส่วนใช้ไม่ได้แยกเก็บและติดป้าย",
      rk="ORA.GEN.205", mt=["DOC","OBS"]),
  dict(d="Tool control is practised (tool accountability check before/after work, calibrated tools in date).",
      th="มีการควบคุมเครื่องมือจริง (นับก่อน-หลังงาน, เครื่องมือสอบเทียบไม่หมดอายุ)",
      rk="ORA.GEN.205", mt=["OBS"], ref="MMSOP Tool Accountability"),
  dict(d="Defects deferred by the AMO follow the agreed procedure/MEL and are communicated to the ATO before flight.",
      th="ข้อบกพร่องที่ defer ทำตามขั้นตอน/MEL และแจ้ง ATO ก่อนทำการบิน",
      rk="ORA.GEN.205", mt=["DOC","INT"]),
 ]),
 ("V4.3","Aerodrome services / บริการสนามบิน (If applicable)",[
  dict(d="Runway/movement area inspections are performed per schedule; defects/NOTAM initiated when required.",
      th="การตรวจทางวิ่ง/พื้นที่เคลื่อนไหวทำตามวาระ และออก NOTAM เมื่อจำเป็น",
      rk="ORA.ATO.140", mt=["DOC","INT"]),
  dict(d="Rescue & firefighting capability and wildlife hazard control are maintained as agreed.",
      th="ขีดความสามารถกู้ภัยดับเพลิงและการควบคุมสัตว์อันตรายคงอยู่ตามข้อตกลง",
      rk="ORA.ATO.140", mt=["OBS","DOC"]),
 ]),
 ("V4.4","Training / examination / medical services (If applicable)","",[
  dict(d="External training/exam/medical services hold current approvals and deliver records back to the ATO in the agreed format and time.",
      th="บริการอบรม/สอบ/แพทย์ภายนอกมีการรับรองปัจจุบัน และส่งบันทึกผลกลับให้ ATO ตามรูปแบบ/เวลาที่ตกลง",
      rk="ORA.GEN.205", mt=["DOC","XCK"]),
 ]),
]),
("V5 – Safety & Quality Interface", "จุดเชื่อมต่อด้านนิรภัยและคุณภาพกับ ATO", [
 ("V5.1","Interface / การเชื่อมโยงระบบ",[
  dict(d="Occurrences/hazards detected by the vendor that affect the ATO are reported to the ATO safety system (evidence of at least the channel being known).",
      th="เหตุการณ์/อันตรายที่ผู้ให้บริการพบและกระทบ ATO ถูกส่งเข้าระบบนิรภัยของ ATO (อย่างน้อยรู้ช่องทาง)",
      rk="ORA.GEN.205", mt=["INT","DOC"],
      how="Ask vendor staff: if you find something unsafe affecting our aircraft/students, what do you do? Answer must match the interface procedure."),
  dict(d="The vendor has its own internal QA/inspection for the service, and results are available to the ATO on request.",
      th="ผู้ให้บริการมีการตรวจสอบคุณภาพภายในของตนเอง และ ATO ขอดูผลได้",
      rk="ORA.GEN.205", mt=["DOC"]),
  dict(d="Findings from previous ATO vendor audits are closed with evidence.",
      th="ข้อบกพร่องจากการตรวจผู้ให้บริการครั้งก่อนปิดแล้วพร้อมหลักฐาน",
      rk="ORA.GEN.150", mt=["DOC"]),
 ]),
]),
("V6 – Records & Performance Monitoring", "บันทึกและการติดตามผลการให้บริการ", [
 ("V6.1","Performance / ผลการให้บริการ",[
  dict(d="Service records delivered to the ATO are complete and retained per the ATO record-keeping requirements.",
      th="บันทึกการให้บริการที่ส่งให้ ATO ครบถ้วนและถูกจัดเก็บตามข้อกำหนดการเก็บบันทึกของ ATO",
      rk="ORA.GEN.220", mt=["DOC"]),
  dict(d="Service performance is monitored (delays, defect recurrence, complaints) and reviewed with the vendor; corrective actions agreed where needed.",
      th="มีการติดตามผลการให้บริการ (ความล่าช้า ข้อบกพร่องซ้ำ ข้อร้องเรียน) และทบทวนร่วมกับผู้ให้บริการ",
      rk="ORA.GEN.205", mt=["DOC","INT"]),
 ]),
]),
]

SAF_PARTS = [
("SA1 – Safety Policy & Organisation", "นโยบายนิรภัยและโครงสร้างองค์กร [OMM]", [
 ("SA1.1","Policy & accountability / นโยบายและความรับผิดชอบ",[
  dict(d="Safety policy is current, signed by the Accountable Manager, published, and staff at all levels can state its key commitments including just culture.",
      th="นโยบายนิรภัยเป็นปัจจุบัน ลงนามโดย AM เผยแพร่จริง และบุคลากรทุกระดับบอกสาระสำคัญได้รวมถึง just culture",
      rk="ORA.GEN.200", mt=["OBS","INT"], ref="OMM 1.1 / OMM 4", dual=1,
      chk=["ลงนามโดย AM คนปัจจุบัน","ติดประกาศ ณ จุดปฏิบัติงาน","สุ่มถามบุคลากร 3 คน ตอบได้"]),
  dict(d="Safety accountabilities and responsibilities of all managers and staff are defined and reflected in actual practice (interviews match the OMM).",
      th="หน้าที่ความรับผิดชอบด้านนิรภัยของผู้บริหารและบุคลากรกำหนดไว้ และการปฏิบัติจริงตรงตาม OMM",
      rk="ORA.GEN.200", mt=["INT","XCK"], ref="OMM 3 / OMM 4", dual=1),
  dict(d="Safety objectives and safety performance indicators (SPIs) are established with targets/alert levels and tracked with real data.",
      th="เป้าหมายนิรภัยและตัวชี้วัด (SPI) กำหนดพร้อมเป้า/ระดับแจ้งเตือน และเก็บข้อมูลจริง",
      rk="ORA.GEN.200", mt=["DOC"], ref="OMM 4.4", dual=1),
  dict(d="Emergency Response Plan is current, contacts verified, roles known, and exercised per schedule with lessons captured.",
      th="ERP เป็นปัจจุบัน เบอร์ติดต่อใช้ได้ บุคลากรรู้บทบาท และซ้อมตามวาระพร้อมบันทึกบทเรียน",
      rk="ORA.GEN.200", mt=["DOC","INT","DEMO"], ref="OMM ERP", dual=1,
      chk=["เบอร์ติดต่อทดสอบแล้วใช้ได้","บุคลากรบอก 3 ขั้นตอนแรกได้","บันทึกการซ้อมล่าสุด","lessons learned นำไปแก้ไข"]),
 ]),
]),
("SA2 – Safety Risk Management", "การจัดการความเสี่ยงด้านนิรภัย [OMM 4]", [
 ("SA2.1","Hazard identification & risk / การชี้บ่งอันตรายและความเสี่ยง",[
  dict(d="Hazard identification is active: voluntary reports exist, FRAE risk assessments completed per flight, and hazards from audits/occurrences feed the register.",
      th="การชี้บ่งอันตรายทำงานจริง: มีรายงานสมัครใจ, FRAE ครบทุกเที่ยวบิน, อันตรายจากการตรวจ/เหตุการณ์เข้าทะเบียน",
      rk="ORA.GEN.200", mt=["DOC","XCK"], ref="OMM 4 / D-0507-FRAE-001", dual=1,
      chk=["รายงานอันตราย 12 เดือน > 0","FRAE สุ่ม 10 เที่ยวครบ","hazard register อัปเดตล่าสุด ≤ 3 เดือน"]),
  dict(d="Risk assessment methodology in the OMM is actually used: risks scored, mitigations assigned with owners/dates, residual risk accepted at the right level.",
      th="ใช้วิธีประเมินความเสี่ยงตาม OMM จริง: ให้คะแนน กำหนดมาตรการ ผู้รับผิดชอบ วันกำหนด และผู้ยอมรับความเสี่ยงถูกระดับ",
      rk="ORA.GEN.200", mt=["DOC"], ref="OMM 4", dual=1),
  dict(d="Management of change is applied to recent changes (new aircraft, manual revisions, new sites/courses) with documented risk assessment.",
      th="ใช้ management of change กับการเปลี่ยนแปลงล่าสุด พร้อมการประเมินความเสี่ยงเป็นเอกสาร",
      rk="ORA.GEN.130", mt=["DOC"], ref="OMM 4 / MOC forms", dual=1),
 ]),
]),
("SA3 – Safety Assurance", "การประกันด้านนิรภัย [OMM 4–5]", [
 ("SA3.1","Monitoring & investigation / การติดตามและการสอบสวน",[
  dict(d="SPIs are measured and reviewed against targets; alert level breaches trigger documented action.",
      th="วัดและทบทวน SPI เทียบเป้า เมื่อแตะระดับแจ้งเตือนมีการดำเนินการเป็นเอกสาร",
      rk="ORA.GEN.200", mt=["DOC"], ref="OMM 4.4", dual=1),
  dict(d="Internal occurrence investigations identify contributing factors and produce corrective actions that are tracked to closure.",
      th="การสอบสวนเหตุการณ์ภายในหาปัจจัยเกี่ยวข้องและออก corrective action ติดตามจนปิด",
      rk="ORA.GEN.160", mt=["DOC"], ref="OMM 4 / occurrence log", dual=1),
  dict(d="Mandatory occurrences reported to CAAT within required timeframes.",
      th="เหตุการณ์ที่ต้องรายงานส่ง กพท. ภายในเวลาที่กำหนด",
      rk="ORA.GEN.160", mt=["XCK"], ref="OMM 4", dual=1),
  dict(d="Internal audit programme (including this checklist system) is executed on schedule and findings are closed via CAR with effectiveness verification.",
      th="โปรแกรมตรวจติดตามภายในดำเนินตามกำหนด และ finding ปิดผ่านระบบ CAR พร้อมทวนสอบประสิทธิผล",
      rk="ORA.GEN.200", mt=["DOC"], ref="OMM 5 / CAR register", dual=1),
  dict(d="Management/safety review meetings occur per schedule with AM participation; decisions and resource allocations recorded and actioned.",
      th="การประชุมทบทวนฝ่ายบริหาร/นิรภัยจัดตามวาระ AM เข้าร่วม มติและการจัดสรรทรัพยากรบันทึกและทำจริง",
      rk="ORA.GEN.200", mt=["DOC","INT"], ref="OMM 4-5", dual=1),
 ]),
]),
("SA4 – Safety Promotion", "การส่งเสริมด้านนิรภัย [OMM 4/8]", [
 ("SA4.1","Training & communication / การอบรมและการสื่อสาร",[
  dict(d="Safety/SMS training delivered to all staff per the training plan; records complete; new staff receive induction safety training before starting duties.",
      th="อบรมนิรภัย/SMS ครบทุกคนตามแผน บันทึกครบ พนักงานใหม่ได้รับก่อนเริ่มงาน",
      rk="ORA.GEN.200", mt=["DOC"], ref="OMM 8 / Staff Training Plan", dual=1),
  dict(d="Safety communication is active: bulletins/meetings/lessons-learned shared; students also receive safety information relevant to them.",
      th="การสื่อสารนิรภัยทำต่อเนื่อง: จดหมายข่าว/การประชุม/บทเรียน และศิษย์การบินได้รับข้อมูลนิรภัยที่เกี่ยวข้อง",
      rk="ORA.GEN.200", mt=["DOC","INT"], ref="OMM 4", dual=1),
 ]),
]),
("SA5 – Flight Operations Safety", "นิรภัยการปฏิบัติการบิน [OMA]", [
 ("SA5.1","Operational compliance / การปฏิบัติตามข้อกำหนดปฏิบัติการ",[
  dict(d="Weather minima (students vs instructors) are applied in daily operations; marginal-day decisions traceable.",
      th="ใช้ weather minima (ศิษย์/ครู) ในปฏิบัติการจริง วันอากาศก้ำกึ่งมีร่องรอยการตัดสินใจ",
      rk="ORA.ATO.230", mt=["XCK"], ref="OMA C.3", dual=1),
  dict(d="Flight authorisation, fuel policy, W&B and performance requirements of the OMA are met on sampled flights.",
      th="การอนุมัติบิน นโยบายเชื้อเพลิง W&B และสมรรถนะตาม OMA ครบในเที่ยวบินที่สุ่ม",
      rk="ORA.ATO.230", mt=["DOC","XCK"], ref="OMA B/C", dual=1,
      chk=["ใบอนุมัติบินสุ่ม 10 ครบ","เชื้อเพลิงตามนโยบาย","W&B คำนวณจริง","สมรรถนะ/ระยะทางวิ่งพิจารณาแล้ว"]),
  dict(d="Aircraft defect handling and tech log practice match OMA B.5.3; no flight with unresolved no-go defects.",
      th="การจัดการข้อบกพร่องและ tech log ตรง OMA B.5.3 ไม่มีการบินทั้งที่มีข้อบกพร่องห้ามบิน",
      rk="ORA.ATO.230", mt=["DOC"], ref="OMA B.5.3", dual=1),
  dict(d="Solo flight supervision and student duty/rest practice comply with the OMA.",
      th="การกำกับการบินเดี่ยวและชั่วโมงปฏิบัติ/พักของศิษย์เป็นไปตาม OMA",
      rk="ORA.ATO.230", mt=["DOC","XCK"], ref="OMA C / D", dual=1),
 ]),
]),
("SA6 – Training Safety", "นิรภัยด้านการฝึก [TM]", [
 ("SA6.1","Training delivery safety / ความปลอดภัยในการฝึก",[
  dict(d="Safety-critical exercises (stall/spin awareness, emergency procedures, first solo requirements) are trained and assessed per the TM sequence.",
      th="แบบฝึกวิกฤตด้านนิรภัย (stall/spin, emergency, ข้อกำหนดก่อนบินเดี่ยว) ฝึกและประเมินตามลำดับใน TM",
      rk="ORA.ATO.125", mt=["DOC","XCK"], ref="TM / PPL course manual", dual=1),
  dict(d="Briefing/debriefing quality sampled: content matches TM, hazards of the lesson discussed, weather/NOTAM covered.",
      th="คุณภาพ briefing/debriefing ที่สุ่ม: เนื้อหาตรง TM, กล่าวถึงอันตรายของบทเรียน, อากาศ/NOTAM ครบ",
      rk="ORA.ATO.125", mt=["OBS"], ref="TM briefing syllabus", dual=1),
  dict(d="Student progress monitoring catches weak performance: unsatisfactory lessons trigger the TM review/repeat process before progressing.",
      th="การติดตามความก้าวหน้าจับนักเรียนอ่อนได้จริง: บทเรียนไม่ผ่านเข้าสู่กระบวนการทบทวน/ซ่อมตาม TM ก่อนไปต่อ",
      rk="ORA.ATO.125", mt=["DOC"], ref="TM / ECA", dual=1),
  dict(d="Instructor standardisation is effective in practice: different FIs teach/assess the same exercise consistently (compare sampled records/observations).",
      th="Standardisation ของครูได้ผลจริง: ครูต่างคนสอน/ประเมินแบบฝึกเดียวกันสม่ำเสมอ",
      rk="ORA.ATO.110", mt=["XCK","OBS"], ref="OMA D.2.8", dual=1),
 ]),
]),
("SA7 – Ground & Facility Safety", "นิรภัยภาคพื้นและสถานที่ [OMM 1.10 / MMSOP]", [
 ("SA7.1","Ground safety / ความปลอดภัยภาคพื้น",[
  dict(d="Ramp/apron operations are safe: FOD control, propeller safety discipline, vehicle rules airside, high-visibility/PPE use.",
      th="ปฏิบัติการลานจอดปลอดภัย: ควบคุม FOD, วินัยเรื่องใบพัด, กติการถในเขต airside, ใช้เสื้อสะท้อนแสง/PPE",
      rk="ORA.GEN.215", mt=["OBS"], ref="MMSOP Vehicle Safety in Airside / PPE", dual=1),
  dict(d="Fire extinguishers, first aid and emergency equipment across the school are in date and accessible; staff know locations.",
      th="ถังดับเพลิง ปฐมพยาบาล และอุปกรณ์ฉุกเฉินทั่วโรงเรียนไม่หมดอายุ เข้าถึงได้ บุคลากรรู้ตำแหน่ง",
      rk="ORA.GEN.215", mt=["OBS","INT"], ref="MMSOP Fire Extinguisher Inspections", dual=1),
  dict(d="Refuelling and fuel storage practice on site complies with the SOP (bonding, no-smoking, drain checks).",
      th="การเติม/จัดเก็บเชื้อเพลิงในพื้นที่เป็นไปตาม SOP",
      rk="ORA.GEN.215", mt=["OBS"], ref="MMSOP Fuel procedures", dual=1),
  dict(d="Security controls protect aircraft and premises after hours (keys, tie-down, locks) per SOP.",
      th="การรักษาความปลอดภัยอากาศยานและสถานที่นอกเวลาทำการเป็นไปตาม SOP (กุญแจ, tie-down, ล็อก)",
      rk="ORA.GEN.140", mt=["OBS"], ref="MMSOP Key Control / Secure Aircraft", dual=1),
 ]),
]),
]

SUR_PARTS = [
("SU1 – Ramp & Flight Line", "ลานจอดและ Flight Line [MMSOP/FSOP]", [
 ("SU1.1","Ramp observation / สังเกตการณ์ลานจอด",[
  dict(d="Pre-flight inspection performed with the checklist in hand, in full, before first flight — including fuel drain/water check and oil check per SOP.",
      th="ตรวจก่อนบินโดยถือ checklist จริง ครบทุกข้อ ก่อนเที่ยวแรก รวมถึง fuel drain ตรวจน้ำ และตรวจน้ำมันเครื่องตาม SOP",
      rk="MMSOP", mt=["OBS"], ref="MMSOP First Flight Preparation / Fuel Drain / Engine Oil"),
  dict(d="Aircraft released from parking correctly: tie-downs, wing cover, pitot cover, control lock and chocks removed; walk-around confirms.",
      th="นำอากาศยานออกจากจุดจอดถูกต้อง: ปลด tie-down, ผ้าคลุมปีก, ปลอก pitot, control lock, chocks ครบ",
      rk="MMSOP", mt=["OBS"], ref="MMSOP Tie-down / Pitot Tube / Control Wheel Lock",
      chk=["Tie-down ปลดครบ","ผ้าคลุม/ปลอก pitot เก็บ","Control lock ปลด","Chocks เก็บ","Fuel selector/master ตามท่าที่กำหนด"]),
  dict(d="FOD check of the operating area; no loose articles, tools or debris on the ramp.",
      th="ตรวจ FOD บริเวณปฏิบัติการ ไม่มีสิ่งของ/เครื่องมือ/เศษวัสดุตกค้าง",
      rk="MMSOP", mt=["OBS"]),
  dict(d="Personnel on the ramp wear high-visibility/PPE and observe propeller safety; ground signals to crew per FSOP.",
      th="บุคลากรบนลานจอดใส่เสื้อสะท้อนแสง/PPE ระวังใบพัด และใช้สัญญาณมือตาม FSOP",
      rk="FSOP", mt=["OBS"], ref="FSOP Signals to Ground Crew / MMSOP PPE"),
  dict(d="Vehicles airside follow SOP rules (speed, routes, parking clear of aircraft).",
      th="ยานพาหนะในเขต airside ทำตามกติกา SOP (ความเร็ว เส้นทาง จอดพ้นอากาศยาน)",
      rk="MMSOP", mt=["OBS"], ref="MMSOP Vehicle Safety in Airside"),
  dict(d="Refuelling observed: bonding connected, extinguisher at hand, no persons on board, uplift recorded.",
      th="การเติมเชื้อเพลิงที่สังเกต: ต่อ bonding, ถังดับเพลิงพร้อม, ไม่มีคนบนเครื่อง, บันทึกการเติม",
      rk="MMSOP", mt=["OBS"], ref="MMSOP Portable Fuel Gallon Operation"),
 ]),
]),
("SU2 – Flight Preparation & Dispatch", "การเตรียมการบินและการปล่อยเที่ยวบิน [FSOP]", [
 ("SU2.1","Dispatch observation / สังเกตการณ์การปล่อยบิน",[
  dict(d="Weather (METAR/TAF) and NOTAM obtained and understood before flight; within applicable minima for the crew composition.",
      th="ได้ข้อมูลอากาศ (METAR/TAF) และ NOTAM ก่อนบิน และอยู่ใน minima ที่ใช้กับผู้ทำการบิน",
      rk="FSOP", mt=["OBS","DOC"], ref="FSOP METAR & TAF / Flight Preparation"),
  dict(d="Flight documents prepared per FSOP: nav log/map prepared, aircraft documents on board, mass & balance computed.",
      th="เอกสารการบินเตรียมตาม FSOP: nav log/แผนที่, เอกสารประจำเครื่องครบ, คำนวณ W&B",
      rk="FSOP", mt=["DOC"], ref="FSOP Flight Document Preparation / Aircraft Documentation",
      chk=["Nav log/แผนที่พร้อม","เอกสารประจำเครื่องครบ","W&B คำนวณ","เชื้อเพลิงพอตามแผน + สำรอง"]),
  dict(d="Flight authorisation signed by an authorised person BEFORE engine start; exercise and crew match the training record plan.",
      th="ใบอนุมัติบินลงนามโดยผู้มีอำนาจก่อนติดเครื่อง แบบฝึกและผู้ทำการบินตรงตามแผนฝึก",
      rk="FSOP", mt=["OBS","XCK"], ref="OMA / FSOP Flight Preparation"),
  dict(d="Fuel monitoring plan established per FSOP (fuel state checks at defined points).",
      th="มีแผนติดตามเชื้อเพลิงตาม FSOP (จุดตรวจสถานะเชื้อเพลิงระหว่างบิน)",
      rk="FSOP", mt=["INT"], ref="FSOP Fuel Monitoring"),
 ]),
]),
("SU3 – Briefing, Instruction & Cockpit Discipline", "การ Briefing และวินัยในห้องนักบิน [FSOP]", [
 ("SU3.1","Briefing & discipline / การ briefing และวินัย",[
  dict(d="Pre-flight/lesson briefing conducted; content and duration per TM; departure brief given per FSOP.",
      th="Briefing ก่อนบิน/บทเรียนทำจริง เนื้อหา-เวลาตาม TM และมี departure brief ตาม FSOP",
      rk="FSOP", mt=["OBS"], ref="FSOP Departure Brief / TM long briefing"),
  dict(d="Checklists used with standard terminology and challenge-response as prescribed; no memory-only normal procedures.",
      th="ใช้ checklist พร้อมศัพท์มาตรฐานตามที่กำหนด ไม่ทำ normal procedures จากความจำล้วน",
      rk="FSOP", mt=["OBS"], ref="FSOP Use of Checklists and Standard Terminology"),
  dict(d="Sterile cockpit observed during critical phases; radio phraseology standard per FSOP.",
      th="รักษา sterile cockpit ช่วงวิกฤต และใช้ radio phraseology มาตรฐานตาม FSOP",
      rk="FSOP", mt=["OBS"], ref="FSOP Sterile Cockpit / Radio Communication Procedures"),
  dict(d="Student/instructor role division during the exercise matches FSOP (controls handover calls, PIC seating).",
      th="การแบ่งบทบาทศิษย์/ครูตรงตาม FSOP (การส่งมอบการควบคุม, ที่นั่ง PIC)",
      rk="FSOP", mt=["OBS"], ref="FSOP Student vs Instructor Responsibilities / Seating of Aircraft PIC"),
 ]),
]),
("SU4 – Circuit / Airborne Observation", "การสังเกตวงจรการบิน [FSOP]", [
 ("SU4.1","Observable airborne conduct / พฤติกรรมการบินที่สังเกตได้",[
  dict(d="Circuit operations observed from the ground conform to FSOP: pattern, spacing, stabilised approaches, go-around when not stabilised.",
      th="วงจรการบินที่สังเกตจากภาคพื้นเป็นไปตาม FSOP: รูปแบบ ระยะห่าง approach นิ่ง และ go-around เมื่อไม่นิ่ง",
      rk="FSOP", mt=["OBS"], ref="FSOP Positioning/Spacing in the Circuit"),
  dict(d="Wind/weather limitations respected for the operation observed (crosswind, student solo limits).",
      th="เคารพข้อจำกัดลม/อากาศสำหรับปฏิบัติการที่สังเกต (crosswind, ขีดจำกัดบินเดี่ยว)",
      rk="FSOP", mt=["OBS","XCK"], ref="FSOP Wind Limitations / OMA C.3"),
  dict(d="R/T monitored on frequency is standard and disciplined; ATC clearances read back.",
      th="การฟังวิทยุพบว่าใช้ถ้อยคำมาตรฐาน มีวินัย และ read back clearance",
      rk="FSOP", mt=["OBS"], ref="FSOP ATC Clearance / Radio Procedures"),
 ]),
]),
("SU5 – Post-flight & Aircraft Securing", "หลังบินและการเก็บอากาศยาน [MMSOP/FSOP]", [
 ("SU5.1","Post-flight observation / สังเกตการณ์หลังบิน",[
  dict(d="Shutdown per checklist; times/fuel recorded; defects found in flight entered in tech log before leaving the aircraft.",
      th="Shutdown ตาม checklist บันทึกเวลา/เชื้อเพลิง และข้อบกพร่องที่พบระหว่างบินลง tech log ก่อนออกจากเครื่อง",
      rk="FSOP", mt=["OBS","DOC"], ref="FSOP Shut Down / After Landing"),
  dict(d="Aircraft secured per MMSOP after last flight: tie-down, control lock, fuel selector, master off, covers, keys returned per key control.",
      th="เก็บอากาศยานตาม MMSOP หลังเที่ยวสุดท้าย: tie-down, control lock, fuel selector, master off, ผ้าคลุม, คืนกุญแจตามระบบ",
      rk="MMSOP", mt=["OBS"], ref="MMSOP Last Flight / Secure Aircraft / Aircraft Key",
      chk=["Tie-down ครบ","Control lock ใส่","Master switch OFF","Fuel selector ตามที่กำหนด","ผ้าคลุม/chocks","กุญแจคืนตามระบบ"]),
  dict(d="Debrief conducted and training record completed/signed on the day.",
      th="Debrief ทำจริง และบันทึกการฝึกกรอก/ลงนามภายในวัน",
      rk="FSOP", mt=["OBS","DOC"]),
 ]),
]),
("SU6 – Solo Flight Supervision", "การกำกับการบินเดี่ยว", [
 ("SU6.1","Solo observation / สังเกตการณ์บินเดี่ยว",[
  dict(d="Solo authorisation and endorsements verified before flight; weather within student minima at dispatch time.",
      th="การอนุมัติบินเดี่ยวและ endorsement ตรวจก่อนบิน อากาศขณะปล่อยอยู่ใน minima ของศิษย์",
      rk="FSOP", mt=["DOC","XCK"]),
  dict(d="Instructor monitors the solo (position known, R/T monitored, able to intervene/recall).",
      th="ครูติดตามการบินเดี่ยว (รู้ตำแหน่ง ฟังวิทยุ สามารถแทรกแซง/เรียกกลับได้)",
      rk="FSOP", mt=["OBS","INT"]),
 ]),
]),
("SU7 – Maintenance Activity", "กิจกรรมซ่อมบำรุง [MMSOP]", [
 ("SU7.1","Maintenance observation / สังเกตการณ์งานซ่อม",[
  dict(d="Work performed under an open work order; current data/manual at the job; steps signed off as completed.",
      th="งานที่ทำมี work order เปิดอยู่ ใช้คู่มือ/ข้อมูลฉบับปัจจุบันหน้างาน และลงนามรายขั้นตอน",
      rk="MMSOP", mt=["OBS","DOC"], ref="MMSOP Work Order / Work Order Prioritization"),
  dict(d="Tool accountability practised: tools checked out/in, count after job, calibrated tools in date.",
      th="Tool accountability ทำจริง: เบิก-คืนเครื่องมือ นับหลังจบงาน เครื่องมือสอบเทียบไม่หมดอายุ",
      rk="MMSOP", mt=["OBS"], ref="MMSOP Tool Accountability"),
  dict(d="PPE worn; ladders inspected before use; pump/ground equipment condition serviceable.",
      th="ใส่ PPE, ตรวจบันไดก่อนใช้, อุปกรณ์ภาคพื้น/ปั๊มสภาพพร้อมใช้",
      rk="MMSOP", mt=["OBS"], ref="MMSOP PPE / Ladder Inspection / Pump Maintenance"),
  dict(d="Logbook entries (airframe/engine/propeller) and CRS completed correctly for finished work.",
      th="บันทึกสมุดปูม (โครงสร้าง/เครื่องยนต์/ใบพัด) และ CRS ของงานที่เสร็จถูกต้องครบถ้วน",
      rk="MMSOP", mt=["DOC"], ref="MMSOP Propeller Logbook / Logbook procedures"),
  dict(d="Fire extinguishers in the work area inspected in date; flammables stored properly.",
      th="ถังดับเพลิงในพื้นที่งานตรวจตามวาระ วัตถุไวไฟจัดเก็บถูกต้อง",
      rk="MMSOP", mt=["OBS"], ref="MMSOP Fire Extinguisher Inspections"),
 ]),
]),
("SU8 – Ground School / Classroom", "ภาคทฤษฎี/ห้องเรียน [TM]", [
 ("SU8.1","Classroom observation / สังเกตการณ์ห้องเรียน",[
  dict(d="Lesson observed matches the timetable and approved TK syllabus reference; qualified TKI delivering.",
      th="คาบเรียนที่สังเกตตรงตารางสอนและหลักสูตร TK ที่อนุมัติ ผู้สอนเป็น TKI ที่มีคุณสมบัติ",
      rk="ORA.ATO.125", mt=["OBS","XCK"], ref="TM / timetable"),
  dict(d="Attendance recorded in real time; training aids used; classroom environment adequate.",
      th="บันทึกการเข้าเรียนแบบเรียลไทม์ ใช้สื่อช่วยสอน สภาพห้องเหมาะสม",
      rk="ORA.ATO.125", mt=["OBS"]),
 ]),
]),
]
