# -*- coding: utf-8 -*-
# On-Site & Implementation Audit checklist — D-0507 Flight Training (ATO)
# Structure: PARTS = [(part_title_EN, part_title_TH, [ (group_no, group_subject, [items...]) ]) ]
# item = dict(d=EN requirement, th=Thai, rk=clause key, mt=[methods], how=verification guidance (EN/TH mixed), ref=manual cross-ref hint)
# methods: OBS=Observe, DOC=Records/Documents, INT=Interview, XCK=Cross-check, DEMO=Demonstration

PARTS = [
# ==================================================================================
("Site 1 – Facilities & Security", "สถานที่ สิ่งอำนวยความสะดวก และการรักษาความปลอดภัย", [
 ("S1.1","Operations room / ห้องปฏิบัติการบิน",[
  dict(d="An operations room is established, staffed during flight operations, and equipped as described in the OMM/OMA (flight authorisation board/system, flight following, communication means).",
       th="มีห้องปฏิบัติการบินที่มีเจ้าหน้าที่ประจำระหว่างทำการบิน พร้อมอุปกรณ์ตามที่ระบุในคู่มือ (บอร์ด/ระบบอนุมัติการบิน, flight following, เครื่องมือสื่อสาร)",
       rk="ORA.GEN.215", mt=["OBS","XCK"],
       how="Walk the ops room during an active flying period. Compare equipment present vs OMM 1.10 / OMA description. Verify flight following board shows current flights. ทดสอบวิทยุ/โทรศัพท์ติดต่ออากาศยานหรือสนามบินได้จริง",
       ref="OMM 1.10 / OMA Part C"),
  dict(d="Current weather information, NOTAM and AIP access is available and actually used for flight planning.",
       th="มีข้อมูลอากาศ NOTAM และ AIP ฉบับปัจจุบันพร้อมใช้งาน และถูกใช้ในการวางแผนการบินจริง",
       rk="ORA.GEN.215", mt=["OBS","DOC"],
       how="Check TAF/METAR source available (terminal/printout), NOTAM briefing evidence attached to recent flight authorisations (sample 5 flights). AIP amendment status current.",
       ref="OMA Part C"),
 ]),
 ("S1.2","Briefing & classroom facilities / ห้องบรรยายและห้องเรียน",[
  dict(d="Briefing facilities (rooms/cubicles) are adequate for the number of students under training and equipped for pre/post-flight briefing.",
       th="ห้อง briefing เพียงพอต่อจำนวนศิษย์การบินที่กำลังฝึก และมีอุปกรณ์สำหรับ briefing ก่อน/หลังบิน",
       rk="ORA.GEN.215", mt=["OBS","XCK"],
       how="Count briefing positions vs current enrolment (cross-check student register). Check whiteboard, charts, aircraft model, syllabus/lesson plan available at point of use.",
       ref="OMM 1.10"),
  dict(d="Classrooms match the declared capacity, with training aids (projector, models, instruments) serviceable; environment (lighting, ventilation, noise) suitable for instruction.",
       th="ห้องเรียนรองรับจำนวนตามที่แจ้งไว้ อุปกรณ์ช่วยสอนใช้งานได้ สภาพแวดล้อม (แสง เสียง อากาศ) เหมาะสมกับการเรียนการสอน",
       rk="ORA.GEN.215", mt=["OBS"],
       how="Inspect each classroom. Operate projector/training aids. Compare room list vs OMM facilities section. ถ่ายรูปประกอบหลักฐาน",
       ref="OMM 1.10"),
  dict(d="Reference library / study area with current regulations (TCAR, AIP), manuals and training publications accessible to instructors and students.",
       th="มีมุมเอกสารอ้างอิง/ห้องสมุดที่มีกฎระเบียบและคู่มือฉบับปัจจุบันให้ครูการบินและศิษย์การบินเข้าถึงได้",
       rk="ORA.GEN.215", mt=["OBS","DOC"],
       how="Spot-check 3 documents for currency (TCAR PEL, OMA, TM revision status vs LEP). Ask a student where to find the training manual.",
       ref="OMM 0 / LEP"),
 ]),
 ("S1.3","Access control & security / การควบคุมการเข้าถึง",[
  dict(d="Access to ATO premises, operational areas and records is controlled as described in the OMM; visitors are managed; critical areas protected.",
       th="การเข้าถึงพื้นที่ปฏิบัติการและเอกสารถูกควบคุมตามที่เขียนไว้ใน OMM มีการจัดการผู้มาเยือน พื้นที่สำคัญได้รับการป้องกัน",
       rk="ORA.GEN.140", mt=["OBS","DEMO","INT"],
       how="Observe entry points, visitor log in use, keys/locks on records room. Ask staff how unauthorised persons are prevented from flight line access. Compare practice vs OMM 1.10 Access.",
       ref="OMM 1.10"),
  dict(d="CAAT right of access is known to staff: personnel can produce certificates, approvals and records on request without delay.",
       th="บุคลากรทราบสิทธิการเข้าตรวจของ กพท. และสามารถนำใบรับรอง/เอกสาร/บันทึกมาแสดงได้ทันทีเมื่อร้องขอ",
       rk="ORA.GEN.140", mt=["INT","DEMO"],
       how="Ask duty ops staff to retrieve ATO certificate, approval schedule and one student file within reasonable time (test drill).",
       ref="OMM 1"),
  dict(d="First aid, fire extinguishers and emergency exits at the facility are serviceable, inspected in date, and unobstructed.",
       th="ชุดปฐมพยาบาล ถังดับเพลิง และทางหนีไฟ พร้อมใช้ ตรวจตามวาระ และไม่มีสิ่งกีดขวาง",
       rk="ORA.GEN.215", mt=["OBS"],
       how="Check extinguisher tags (inspection date), first-aid kit contents/expiry, exit routes clear. Sample 3 locations.",
       ref="OMM 1.10 / ERP"),
 ]),
 ("S1.4","Controlled documents at point of use / เอกสารควบคุม ณ จุดใช้งาน",[
  dict(d="Controlled copies of OMM, OMA, TM and forms at points of use are the current revision; obsolete revisions are removed.",
       th="สำเนาควบคุมของ OMM OMA TM และแบบฟอร์ม ณ จุดใช้งานเป็นฉบับล่าสุด และเก็บฉบับยกเลิกออกแล้ว",
       rk="ORA.ATO.130", mt=["DOC","XCK"],
       how="Pick 3 locations (ops room, briefing room, aircraft). Compare copy number + revision vs Distribution List and LEP. Look for uncontrolled photocopies in use. ตรวจว่าแบบฟอร์มที่ใช้ตรงกับ List of Effective Forms",
       ref="OMM 0.6-0.7 / Distribution List"),
  dict(d="Manual amendment process is functioning: latest CAAT-approved amendment incorporated, revision bars and record of revision filled in.",
       th="กระบวนการแก้ไขคู่มือทำงานจริง: การแก้ไขที่ กพท. อนุมัติล่าสุดถูกผนวกแล้ว มี revision bar และบันทึกการแก้ไขครบ",
       rk="ORA.ATO.130", mt=["DOC"],
       how="Trace the latest approved amendment (e.g. OMA 2026 V3) from CAAT approval letter → record of revision → LEP → changed pages present.",
       ref="OMM 0 / OMA 0"),
 ]),
]),
# ==================================================================================
("Site 2 – Training Aircraft & FSTD", "อากาศยานฝึกและเครื่องช่วยฝึกจำลองการบิน", [
 ("S2.1","Fleet & airworthiness / ฝูงบินและความสมควรเดินอากาศ",[
  dict(d="Training aircraft fleet matches the OMA/TM (types, registration, equipment fit adequate for the training courses conducted).",
       th="ฝูงบินตรงกับที่ระบุใน OMA/TM (แบบ ทะเบียน อุปกรณ์ครบตามภารกิจฝึก)",
       rk="ORA.ATO.135", mt=["OBS","XCK"],
       how="Compare aircraft on the line vs OMA Part B aircraft list. Verify equipment required for each course phase (e.g. radio nav for navigation exercises) installed and serviceable.",
       ref="OMA Part B"),
  dict(d="For each training aircraft: Certificate of Airworthiness, Certificate of Registration, ARC, insurance and radio licence are current; documents carried/available as required.",
       th="อากาศยานฝึกแต่ละลำ: CofA, CofR, ARC, ประกันภัย, ใบอนุญาตวิทยุ ยังไม่หมดอายุ และมีเอกสารประจำเครื่องครบ",
       rk="ORA.ATO.135", mt=["DOC"],
       how="Sample every aircraft (small fleet) or min 2. Record expiry dates. Check documents on board vs OMA required document list.",
       ref="OMA Part B"),
  dict(d="Maintenance status: aircraft released to service (CRS) after last scheduled maintenance; next maintenance due not exceeded; maintenance contract with AMO active.",
       th="สถานะซ่อมบำรุง: มี CRS หลังซ่อมบำรุงตามวาระล่าสุด ยังไม่เกินกำหนดครั้งถัดไป และสัญญากับหน่วยซ่อม (AMO) ยังมีผล",
       rk="ORA.ATO.135", mt=["DOC","XCK"],
       how="Cross-check tech log hours vs maintenance due list. Verify CRS signature/approval number. Confirm AMO approval current (ORA.GEN.205 contracted activity oversight).",
       ref="OMA Part B / MCM"),
  dict(d="Technical log / defect reporting is used in practice per OMA: open defects properly deferred (MEL where applicable), no flights with unresolved no-go defects.",
       th="สมุด tech log และการรายงานข้อบกพร่องถูกใช้จริงตาม OMA: ข้อบกพร่องค้างถูก defer อย่างถูกต้อง ไม่มีการบินทั้งที่มีข้อบกพร่องห้ามบิน",
       rk="ORA.ATO.135", mt=["DOC","INT"],
       how="Review last 30 days of tech log entries for 2 aircraft. Trace one defect from report → rectification/deferral → release. Ask an FI how they report a defect found during preflight.",
       ref="OMA B.5.3 / MEL"),
  dict(d="Daily/preflight check practice matches the checklist in use; fuel and oil uplift recorded; W&B within limits for training configuration.",
       th="การตรวจก่อนบิน/ประจำวันทำตาม checklist จริง บันทึกการเติมเชื้อเพลิง/น้ำมัน และ W&B อยู่ในขีดจำกัด",
       rk="ORA.ATO.135", mt=["OBS","DOC"],
       how="Observe one student/FI preflight against the aircraft checklist. Sample 5 journey-log pages for fuel/oil records and W&B evidence.",
       ref="OMA B.5 / B.9"),
 ]),
 ("S2.2","FSTD (if applicable) / เครื่องช่วยฝึกจำลองการบิน (ถ้ามี)",[
  dict(d="FSTD qualification certificate current; device operated and maintained per the qualification basis; usage recorded in training records.",
       th="ใบรับรองคุณสมบัติ FSTD ยังไม่หมดอายุ ใช้งานและบำรุงรักษาตามเกณฑ์ และบันทึกการใช้ในบันทึกการฝึก",
       rk="ORA.FSTD.105", mt=["DOC","OBS"],
       how="If no FSTD is operated → mark N/A both dimensions. Otherwise check certificate, defect log, daily functional check records.",
       ref="OMM Part 2 FSTD"),
 ]),
]),
# ==================================================================================
("Site 3 – Aerodrome & Operating Sites", "สนามบินและพื้นที่ปฏิบัติการ", [
 ("S3.1","Base aerodrome / สนามบินหลัก",[
  dict(d="Base aerodrome characteristics match the OMA (runway dimensions/surface, obstacle environment, wind indicator, circuit procedures) and remain adequate for the training conducted.",
       th="ลักษณะสนามบินหลักตรงตาม OMA (ขนาด/ผิวทางวิ่ง สิ่งกีดขวาง เครื่องบอกทิศทางลม แบบวงจรการบิน) และยังเหมาะสมกับการฝึก",
       rk="ORA.ATO.140", mt=["OBS","XCK"],
       how="Walk/drive inspection of runway, taxiway, apron condition. Compare vs OMA aerodrome data. Verify wind indicator visible from air, signage adequate.",
       ref="OMA Part C"),
  dict(d="Emergency equipment at the operating site (fire extinguisher, crash/rescue kit, first aid, emergency contact list) is available, in date and staff know its location.",
       th="อุปกรณ์ฉุกเฉิน ณ พื้นที่ปฏิบัติการ (ถังดับเพลิง ชุดกู้ภัย ปฐมพยาบาล รายชื่อติดต่อฉุกเฉิน) พร้อมใช้ ไม่หมดอายุ และเจ้าหน้าที่ทราบตำแหน่ง",
       rk="ORA.ATO.140", mt=["OBS","INT"],
       how="Inspect equipment. Ask 2 staff members where the crash kit is and what the first actions after an accident are (test ERP knowledge).",
       ref="OMA Part C / ERP"),
  dict(d="Fuelling arrangements and fire precautions during refuelling follow the OMA procedure.",
       th="การเติมเชื้อเพลิงและการป้องกันอัคคีภัยระหว่างเติมทำตามขั้นตอนใน OMA",
       rk="ORA.ATO.140", mt=["OBS"],
       how="Observe one refuelling: bonding/earthing, extinguisher at hand, no pax on board, fuel quality check (water drain sample).",
       ref="OMA Part B/C"),
  dict(d="Radio coverage and ATS/UNICOM arrangements function as described; agreement with aerodrome operator (if third-party) is current.",
       th="การติดต่อวิทยุและบริการจราจรทางอากาศเป็นไปตามที่ระบุ และข้อตกลงกับผู้ดำเนินการสนามบิน (ถ้ามี) ยังมีผล",
       rk="ORA.ATO.140", mt=["DEMO","DOC"],
       how="Radio check from ops room/aircraft. Sight the aerodrome use agreement / letter of agreement and expiry.",
       ref="OMA Part C"),
 ]),
]),
# ==================================================================================
("Site 4 – Personnel in Practice", "บุคลากร: คุณสมบัติและการปฏิบัติหน้าที่จริง", [
 ("S4.1","Nominated persons / ผู้ดำรงตำแหน่งหลัก",[
  dict(d="Accountable Manager, Head of Training, CFI, CTKI, Safety Manager and Compliance Monitoring Manager are in post as approved, and each can explain their duties as written in the OMM.",
       th="AM, HT, CFI, CTKI, SM และ CMM ดำรงตำแหน่งจริงตามที่ได้รับความเห็นชอบ และอธิบายหน้าที่ของตนตาม OMM ได้",
       rk="ORA.GEN.210", mt=["INT","XCK"],
       how="Interview each nominated person (15 min): duties, deputisation when absent, reporting lines vs OMM organisation chart. Cross-check CAAT approval (Form acceptance) for each post holder.",
       ref="OMM 3.2 / Org chart"),
  dict(d="Deputy/absence arrangements work in practice: recent absences were covered by the deputies named in the OMM.",
       th="การมอบหมายผู้ทำการแทนใช้ได้จริง: การลา/ไม่อยู่ล่าสุดมีผู้ทำการแทนตามที่ระบุใน OMM",
       rk="ORA.GEN.210", mt=["INT","DOC"],
       how="Ask HT for a recent example (leave/travel) and sight the delegation record or authorisation trail during that period.",
       ref="OMM 3.2"),
 ]),
 ("S4.2","Instructor qualifications & currency / คุณสมบัติและความต่อเนื่องของครูการบิน",[
  dict(d="Sample of FI files: licence, FI rating, class rating, medical certificate and English language proficiency all current; privileges match the instruction actually given.",
       th="สุ่มแฟ้มครูการบิน: ใบอนุญาต, FI rating, class rating, ใบสำคัญแพทย์, ELP ยังไม่หมดอายุ และสิทธิตรงกับการสอนที่ทำจริง",
       rk="ORA.ATO.110", mt=["DOC","XCK"],
       how="Sample ALL FIs if ≤5, else 50%. Build expiry matrix. Cross-check: an FI who flew student X on date Y (from flight records) held valid privileges on that date.",
       ref="OMA Part D / personnel files"),
  dict(d="Instructor standardisation and proficiency checks are performed on schedule (D-0507-PCR-FI / STR records complete and in date).",
       th="การ standardisation และ proficiency check ของครูการบินทำตามวาระ (บันทึก D-0507-PCR-FI / STR ครบและเป็นปัจจุบัน)",
       rk="ORA.ATO.110", mt=["DOC"],
       how="Check PCR-FI and Standardisation Training Records for every FI vs the schedule in OMA Part D. List any overdue checks as findings.",
       ref="OMA D.2.8 / PCR-FI, STR forms"),
  dict(d="Instructor-to-student ratio and flight/duty limits in actual scheduling comply with the OMA; instructor duty records maintained.",
       th="สัดส่วนครูต่อศิษย์และขีดจำกัดชั่วโมงบิน/ปฏิบัติหน้าที่ในตารางจริงเป็นไปตาม OMA และมีบันทึกเวลาปฏิบัติหน้าที่ของครู",
       rk="ORA.ATO.110", mt=["XCK","DOC"],
       how="Take one busy month: compute each FI's flight hours & duty days from authorisation sheets vs OMA limits. Check current student allocation list per FI.",
       ref="OMA Part A/D"),
  dict(d="TKI qualifications on file; theoretical knowledge instruction actually delivered by qualified TKIs per the approved course.",
       th="คุณสมบัติครูภาควิชาการครบตามแฟ้ม และการสอนภาควิชาการดำเนินการโดย TKI ที่มีคุณสมบัติตามหลักสูตรที่ได้รับอนุมัติ",
       rk="ORA.ATO.110", mt=["DOC","XCK"],
       how="Sample TKI files (PCR-TKI). Cross-check ground school timetable instructor names vs qualified TKI list.",
       ref="OMA Part D / PCR-TKI"),
 ]),
 ("S4.3","Staff training implementation / การฝึกอบรมบุคลากรที่ทำจริง",[
  dict(d="Initial, refresher, standardisation and safety training defined in OMA Part D have actually been delivered — attendance records and evaluation on file for each staff member.",
       th="การอบรม initial/refresher/standardisation/safety ตาม OMA Part D จัดจริง มีบันทึกการเข้าอบรมและการประเมินของบุคลากรแต่ละคน",
       rk="ORA.GEN.210", mt=["DOC","INT"],
       how="Build a training matrix: staff × required courses vs records (RTR forms, Staff Training Plan). Interview one recent joiner about their induction content.",
       ref="OMA Part D / D-0507-RTR-001, Staff Training Plan"),
  dict(d="SMS training: all personnel have received safety training appropriate to their role; records current per the training plan.",
       th="บุคลากรทุกคนผ่านการอบรม SMS ตามบทบาท และบันทึกเป็นปัจจุบันตามแผนการอบรม",
       rk="ORA.GEN.200", mt=["DOC","INT"],
       how="Check SMS training records vs staff list. Ask 2 random staff: how do you report a hazard? (answers should match the manual).",
       ref="OMM 4 / OMM 8"),
 ]),
]),
# ==================================================================================
("Site 5 – Records & Record-keeping in Practice", "ระบบบันทึกและการเก็บรักษาจริง", [
 ("S5.1","Student training records / บันทึกการฝึกของศิษย์การบิน",[
  dict(d="Sample of student files: enrolment documents, pre-entry checks (age, medical class, ELP), training agreement and ID all present and verified before training started.",
       th="สุ่มแฟ้มศิษย์การบิน: เอกสารรับเข้า การตรวจคุณสมบัติก่อนเข้า (อายุ ใบสำคัญแพทย์ ELP) สัญญาฝึก และบัตรประจำตัว ครบและตรวจก่อนเริ่มฝึกจริง",
       rk="ORA.ATO.145", mt=["DOC"],
       how="Sample ≥3 active + 2 graduated students. Verify medical class/validity date precedes first flight date. รายการใดขาดให้บันทึกเป็น finding พร้อมชื่อแฟ้ม",
       ref="TM / PPL course manual 2.1"),
  dict(d="Flight training records complete and signed: each flight has lesson number, exercises, duration, instructor signature and student progress grading matching the TM syllabus sequence.",
       th="บันทึกการฝึกบินครบและมีลายเซ็น: ทุกเที่ยวบินมีหมายเลขบทเรียน แบบฝึก เวลา ลายเซ็นครู และการประเมินความก้าวหน้าตามลำดับใน TM",
       rk="ORA.ATO.120", mt=["DOC","XCK"],
       how="Trace 2 students end-to-end: every logged flight vs TM lesson sequence; check pre-solo requirements (written test, weather, endorsement) completed before first solo date.",
       ref="TM / student records"),
  dict(d="Theoretical knowledge progress: attendance, progress tests and course completion certificates on file and consistent with ground school timetable.",
       th="ภาควิชาการ: บันทึกการเข้าเรียน ผลสอบความก้าวหน้า และใบรับรองจบภาคทฤษฎี ครบและสอดคล้องกับตารางสอนจริง",
       rk="ORA.ATO.120", mt=["DOC","XCK"],
       how="Same 2 students: attendance % vs course requirement, progress test scores vs pass mark in TM, completion certificate before TK exam application.",
       ref="TM / PPL course manual"),
  dict(d="Flight time cross-check: student logbook, training record, aircraft journey log and authorisation sheet agree for sampled flights.",
       th="ตรวจไขว้ชั่วโมงบิน: สมุดปูมศิษย์ บันทึกการฝึก journey log ของอากาศยาน และใบอนุมัติการบิน ตรงกันในเที่ยวบินที่สุ่ม",
       rk="ORA.ATO.120", mt=["XCK"],
       how="Pick 5 flights across different dates/aircraft: all four sources must agree on date, times, crew. Any mismatch = finding (record integrity).",
       ref="OMA Part A / records system"),
 ]),
 ("S5.2","Storage, retention & protection / การจัดเก็บ การเก็บรักษา และการป้องกัน",[
  dict(d="Records are stored securely with protection from damage, alteration and theft; retention periods met (training records kept per TCAR after course completion).",
       th="บันทึกถูกจัดเก็บอย่างปลอดภัย ป้องกันความเสียหาย/แก้ไข/สูญหาย และเก็บครบตามระยะเวลาที่ TCAR กำหนดหลังจบหลักสูตร",
       rk="ORA.GEN.220", mt=["OBS","DOC"],
       how="Inspect records room: lock, fire protection, indexing. Request one file of a student who completed >1 year ago (retrieval test). Verify retention rule in OMM matches practice.",
       ref="OMM / OMA record-keeping section"),
  dict(d="Electronic records (if used) are backed up; backup actually restorable; access rights limited to authorised persons.",
       th="บันทึกอิเล็กทรอนิกส์ (ถ้ามี) มีการสำรองข้อมูล ทดสอบกู้คืนได้จริง และจำกัดสิทธิเข้าถึงเฉพาะผู้ได้รับอนุญาต",
       rk="ORA.GEN.220", mt=["DEMO","INT"],
       how="Ask admin to show backup log and restore one sample file. Review user access list vs authorised roles.",
       ref="OMM record-keeping"),
  dict(d="FRAE flight risk assessment forms are completed for flights as required and retained; risk scores and Go/No-Go decisions documented.",
       th="แบบ FRAE ถูกกรอกจริงทุกเที่ยวบินตามข้อกำหนดและจัดเก็บไว้ พร้อมคะแนนความเสี่ยงและการตัดสินใจ Go/No-Go",
       rk="ORA.GEN.200", mt=["DOC","XCK"],
       how="Sample 10 recent flights from authorisation sheet → matching FRAE form exists, scored, signed by authorising FI. Check any high-score flight had mitigation/approval per procedure.",
       ref="D-0507-FRAE-001 / OMM 4"),
 ]),
]),
# ==================================================================================
("Site 6 – SMS Implementation", "การนำระบบจัดการด้านนิรภัย (SMS) ไปปฏิบัติจริง", [
 ("S6.1","Safety policy & organisation / นโยบายและโครงสร้างนิรภัย",[
  dict(d="Safety policy is signed by the current Accountable Manager, displayed/communicated, and staff can state its key commitments (including just culture).",
       th="นโยบายนิรภัยลงนามโดย AM คนปัจจุบัน เผยแพร่จริง และบุคลากรบอกสาระสำคัญได้ (รวมถึง just culture)",
       rk="ORA.GEN.200", mt=["OBS","INT"],
       how="Sight displayed policy (check signatory = current AM). Ask 3 staff: what happens if you report your own error? (answer should reflect just culture).",
       ref="OMM 1.1 / 4"),
  dict(d="Safety Manager is active in the role; safety committee / Safety Action Group meets per the schedule in the OMM — minutes, attendance and action tracking on file.",
       th="SM ปฏิบัติหน้าที่จริง คณะกรรมการนิรภัย/SAG ประชุมตามวาระใน OMM มีรายงานการประชุม ผู้เข้าร่วม และการติดตามข้อสั่งการ",
       rk="ORA.GEN.200", mt=["DOC","INT"],
       how="Review last 4 meeting minutes vs required frequency. Pick 2 open actions: verify follow-up to closure. Interview SM on current top risks.",
       ref="OMM 4"),
 ]),
 ("S6.2","Hazard reporting & risk management / การรายงานอันตรายและการจัดการความเสี่ยง",[
  dict(d="Hazard/occurrence reporting system is used in practice: reports exist, are investigated, feedback given to reporters, and the hazard register is maintained and current.",
       th="ระบบรายงานอันตราย/เหตุการณ์ถูกใช้จริง: มีรายงาน มีการสอบสวน มี feedback ถึงผู้รายงาน และทะเบียนอันตราย (hazard register) เป็นปัจจุบัน",
       rk="ORA.GEN.200", mt=["DOC","INT"],
       how="Count reports in last 12 months (zero reports at an active ATO is itself a red flag — reporting culture). Trace 2 reports: report → risk assessment → mitigation → feedback. Check register review date.",
       ref="OMM 4 / hazard register"),
  dict(d="Risk assessments are performed for identified hazards and for changes (new aircraft, new training site, new course) — management of change records exist.",
       th="มีการประเมินความเสี่ยงสำหรับอันตรายที่พบและการเปลี่ยนแปลง (อากาศยานใหม่ พื้นที่ใหม่ หลักสูตรใหม่) — มีบันทึก management of change",
       rk="ORA.GEN.130", mt=["DOC"],
       how="Identify last significant change (e.g. manual V3 revision, new aircraft) and sight the change risk assessment. If none ever documented → implementation gap.",
       ref="OMM 4 / MOC records"),
  dict(d="Safety performance indicators (SPIs) are being measured and reviewed against targets/alert levels as defined in the OMM.",
       th="มีการเก็บและทบทวนตัวชี้วัดนิรภัย (SPI) เทียบเป้าหมาย/ระดับแจ้งเตือนตามที่กำหนดใน OMM",
       rk="ORA.GEN.200", mt=["DOC"],
       how="Sight the current SPI dashboard/report and the last review where an SPI was discussed. Verify data actually collected (not blank template).",
       ref="OMM 4.4"),
 ]),
 ("S6.3","Occurrence reporting to CAAT & immediate reaction / การรายงานต่อ กพท.",[
  dict(d="Mandatory occurrences were reported to CAAT within the required timeframe; internal investigation completed and corrective actions taken.",
       th="เหตุการณ์ที่ต้องรายงานถูกส่งถึง กพท. ภายในเวลาที่กำหนด มีการสอบสวนภายในและแก้ไขแล้ว",
       rk="ORA.GEN.160", mt=["DOC","XCK"],
       how="Cross-check internal occurrence log vs CAAT submissions (report reference/date). If no occurrences in period, verify staff know the reporting criteria & 72-hr/timeframe rule (interview).",
       ref="OMM 4 / occurrence log"),
  dict(d="Safety directives / airworthiness directives / CAAT safety decisions are received, actioned and closed with evidence (immediate reaction capability).",
       th="Safety directives / AD / ข้อสั่งการของ กพท. ถูกรับ ดำเนินการ และปิดพร้อมหลักฐาน",
       rk="ORA.GEN.155", mt=["DOC"],
       how="Sight the register of received directives, pick the latest one, trace action taken and closure date.",
       ref="OMM 4 / correspondence file"),
 ]),
 ("S6.4","Emergency response / แผนตอบสนองภาวะฉุกเฉิน",[
  dict(d="Emergency Response Plan is current (contact numbers verified), staff know their roles, and a drill/exercise has been conducted per the schedule with lessons recorded.",
       th="ERP เป็นปัจจุบัน (เบอร์ติดต่อใช้ได้จริง) บุคลากรรู้บทบาท และมีการซ้อมตามวาระพร้อมบันทึกบทเรียน",
       rk="ORA.GEN.200", mt=["DOC","INT","DEMO"],
       how="Call-test 2 numbers from the ERP contact list. Ask duty staff their first 3 actions after an aircraft accident. Sight last drill record and follow-up items.",
       ref="OMM / ERP"),
 ]),
]),
# ==================================================================================
("Site 7 – Compliance Monitoring in Practice", "การติดตามการปฏิบัติตามข้อกำหนดที่ทำจริง", [
 ("S7.1","Audit programme execution / การดำเนินโปรแกรมตรวจติดตาม",[
  dict(d="The annual audit plan/programme covers all areas and applicable requirements; audits actually performed on schedule with reports on file.",
       th="แผนตรวจติดตามประจำปีครอบคลุมทุกพื้นที่/ข้อกำหนด และมีการตรวจจริงตามกำหนดพร้อมรายงาน",
       rk="ORA.GEN.200", mt=["DOC"],
       how="Compare audit plan vs completed audit reports (last 12-24 months). Identify overdue audits. Verify checklists used and objective evidence recorded in reports.",
       ref="OMM 5 / audit plan"),
  dict(d="Findings from internal and CAAT audits are managed to closure: root cause analysis, corrective action, verification of effectiveness, within target dates.",
       th="ข้อบกพร่องจากการตรวจภายในและจาก กพท. ถูกจัดการจนปิด: วิเคราะห์สาเหตุราก แก้ไข ทวนสอบประสิทธิผล ภายในกำหนด",
       rk="ORA.GEN.150", mt=["DOC"],
       how="Trace ALL open findings + 3 closed ones: finding → root cause → CA → evidence → closure sign-off. Overdue CAs = finding. รวมข้อบกพร่องจากการตรวจของ กพท. รอบล่าสุด (Findings_PageRef)",
       ref="OMM 5 / CAPA log"),
  dict(d="Compliance Monitoring Manager independence is real in practice (does not audit own work); auditors used are those on the approved list with training records.",
       th="ความเป็นอิสระของ CMM เกิดขึ้นจริง (ไม่ตรวจงานตนเอง) และผู้ตรวจอยู่ในบัญชีที่กำหนดพร้อมบันทึกการอบรม",
       rk="ORA.GEN.200", mt=["DOC","INT"],
       how="Review who audited what vs role conflicts. Sight auditor list and their audit training evidence per OMM 5.1.",
       ref="OMM 5.1"),
  dict(d="Management review / Accountable Manager oversight happens as scheduled: AM has reviewed compliance and safety performance and allocated resources where needed.",
       th="การทบทวนโดยฝ่ายบริหาร/AM เกิดขึ้นตามวาระ: AM ได้ทบทวนผลด้าน compliance และนิรภัย และจัดสรรทรัพยากรเมื่อจำเป็น",
       rk="ORA.GEN.200", mt=["DOC","INT"],
       how="Sight last management review minutes with AM attendance. Interview AM: awareness of current findings and top safety risks.",
       ref="OMM 4-5"),
  dict(d="Regulatory watch: a process is actively tracking TCAR/CAAT amendments and feeding required manual changes (evidence of recent amendment assessments).",
       th="มีการติดตามการแก้ไข TCAR/ประกาศ กพท. อย่างต่อเนื่อง และนำมาประเมินผลกระทบต่อคู่มือ (มีหลักฐานการประเมินครั้งล่าสุด)",
       rk="ORA.GEN.120", mt=["DOC","INT"],
       how="Ask CMM how a new CAAT regulation reaches the manuals. Sight the assessment of TCAR PEL Part ORA Rev 00 (OCT 2024) impact — this GAP analysis itself is evidence.",
       ref="OMM 5 / regulation register"),
 ]),
]),
# ==================================================================================
("Site 8 – Training Operations Observation", "สังเกตการณ์การปฏิบัติการฝึกจริง", [
 ("S8.1","Flight authorisation & preparation / การอนุมัติและเตรียมการบิน",[
  dict(d="Flight authorisation is signed by an authorised person BEFORE each training flight; authorisation sheet content matches the OMA procedure.",
       th="ทุกเที่ยวบินฝึกมีผู้มีอำนาจลงนามอนุมัติก่อนบิน และเนื้อหาใบอนุมัติตรงตามขั้นตอนใน OMA",
       rk="ORA.ATO.125", mt=["OBS","DOC"],
       how="Observe the morning launch: authorisation signed before engine start? Sample 10 past sheets: signatures, times, aircraft, exercise codes complete.",
       ref="OMA Part A/C"),
  dict(d="Pre-flight preparation is done per OMA: weather + NOTAM briefing, W&B and performance calculation, fuel plan — evidenced for each observed flight.",
       th="การเตรียมการบินทำตาม OMA: brief อากาศ+NOTAM คำนวณ W&B/สมรรถนะ แผนเชื้อเพลิง — มีหลักฐานทุกเที่ยวบินที่สังเกต",
       rk="ORA.ATO.125", mt=["OBS","DOC"],
       how="Shadow one student+FI through full pre-flight process. Verify calculations actually done (not pencil-whipped) — recompute one W&B.",
       ref="OMA Part B/C"),
  dict(d="Weather minima applied in practice: observed/planned flights respect student vs instructor minima in the OMA; a marginal-weather decision trail exists.",
       th="ใช้ weather minima จริง: เที่ยวบินที่สังเกต/วางแผนเคารพ minima ของศิษย์กับครูตาม OMA และมีร่องรอยการตัดสินใจในวันอากาศก้ำกึ่ง",
       rk="ORA.ATO.125", mt=["XCK","INT"],
       how="Pick 2 past marginal-weather days (from METAR history): what flights ran? Were solo flights within student minima? Ask duty FI how a no-go decision is recorded.",
       ref="OMA C.3"),
 ]),
 ("S8.2","Instruction delivery vs approved syllabus / การสอนตรงตามหลักสูตรที่อนุมัติ",[
  dict(d="Observed pre-flight (long) briefing follows the TM briefing syllabus content and duration; training aids used.",
       th="การ briefing ที่สังเกตเป็นไปตามเนื้อหาและเวลาของ long briefing ใน TM และใช้สื่อช่วยสอน",
       rk="ORA.ATO.125", mt=["OBS"],
       how="Sit in on one long briefing. Score content vs TM/PPL course manual briefing syllabus for that lesson. Note duration vs published hours.",
       ref="TM / PPL A1 long briefing syllabus"),
  dict(d="Observed ground school lesson matches the approved TK syllabus and lesson plan; student attendance recorded in real time.",
       th="คาบเรียนภาคทฤษฎีที่สังเกตตรงกับหลักสูตร TK และแผนการสอนที่อนุมัติ มีการบันทึกการเข้าเรียนจริง",
       rk="ORA.ATO.125", mt=["OBS","XCK"],
       how="Observe 30+ min of one class. Compare topic vs timetable vs TM syllabus reference. Check attendance sheet completed during (not after) class.",
       ref="TM / Lesson Plan"),
  dict(d="Training sequence in practice follows the TM: no student found flying exercises out of sequence or beyond authorised phase without documented HT approval.",
       th="ลำดับการฝึกจริงเป็นไปตาม TM: ไม่พบศิษย์บินข้ามลำดับหรือเกิน phase ที่ได้รับอนุญาตโดยไม่มีการอนุมัติของ HT เป็นลายลักษณ์อักษร",
       rk="ORA.ATO.125", mt=["XCK"],
       how="From the 2 traced student files (Site 5): flag any out-of-sequence lessons and check for documented deviation approval.",
       ref="TM / student records"),
  dict(d="Solo flight supervision: pre-solo checks completed, FI authorises and monitors each solo, solo conducted within limitations (weather, area, duration).",
       th="การบินเดี่ยว: ตรวจก่อนบินเดี่ยวครบ ครูอนุมัติและติดตามทุกเที่ยว และบินภายในข้อจำกัด (อากาศ พื้นที่ เวลา)",
       rk="ORA.ATO.125", mt=["DOC","OBS"],
       how="Sample 3 recent solo flights: endorsement, FI presence/monitoring arrangement, weather at time vs student minima (pull METAR).",
       ref="TM / OMA C"),
  dict(d="Post-flight debrief and progress grading are done after each flight and recorded before the next lesson; failing progress triggers the review process in the TM.",
       th="มี debrief และการประเมินหลังบินทุกเที่ยว บันทึกก่อนบทเรียนถัดไป และผลไม่ผ่านเข้าสู่กระบวนการทบทวนตาม TM",
       rk="ORA.ATO.125", mt=["OBS","DOC"],
       how="Observe one debrief. In sampled files: any 'unsatisfactory' lesson followed by the required repeat/review action? Progress review board records exist?",
       ref="TM / ECA assessment standards"),
 ]),
 ("S8.3","Examinations & tests in practice / การสอบและทดสอบที่ทำจริง",[
  dict(d="Internal progress tests and pre-exam assessments are conducted, marked and secured (question bank control) as described in the TM.",
       th="การสอบความก้าวหน้าและ pre-exam ดำเนินการ ตรวจ และควบคุมข้อสอบ (คลังข้อสอบ) ตามที่ระบุใน TM",
       rk="ORA.ATO.125", mt=["DOC","OBS"],
       how="Sight question bank access control. Sample marked test papers vs answer keys and pass marks. Check invigilation records.",
       ref="TM / ECA"),
  dict(d="Skill test recommendations: students are recommended only after completing all required training; recommendation forms signed by HT/CFI as required.",
       th="การส่งสอบภาคปฏิบัติ: ศิษย์ถูกส่งสอบเมื่อฝึกครบตามหลักสูตรเท่านั้น และแบบ recommendation ลงนามโดย HT/CFI ตามที่กำหนด",
       rk="ORA.ATO.125", mt=["DOC","XCK"],
       how="For last 2 skill-test candidates: verify total hours & syllabus completion vs TM minima on the date of recommendation.",
       ref="TM / PPL course manual 6"),
 ]),
]),
# ==================================================================================
("Site 9 – Contracted Activities & Certificate Scope", "กิจกรรมจ้างช่วงและขอบเขตใบรับรอง", [
 ("S9.1","Contracted activities oversight / การกำกับดูแลงานจ้างช่วง",[
  dict(d="All contracted activities (maintenance, ground handling, medical, exam services, fuel) are listed as in the OMM, contracts current, and the ATO exercises documented oversight of each contractor.",
       th="กิจกรรมจ้างช่วงทั้งหมด (ซ่อมบำรุง ภาคพื้น การแพทย์ บริการสอบ เชื้อเพลิง) ตรงตามที่ระบุใน OMM สัญญายังมีผล และ ATO กำกับดูแลผู้รับจ้างโดยมีหลักฐาน",
       rk="ORA.GEN.205", mt=["DOC","XCK"],
       how="Compare actual contractors in use vs OMM contracted-activities list. Sight each contract validity + latest oversight evidence (audit, review meeting, performance check of AMO).",
       ref="OMM / contracts file"),
 ]),
 ("S9.2","Certificate, approvals & changes / ใบรับรองและการเปลี่ยนแปลง",[
  dict(d="ATO certificate (FTO-0007) and training course approvals are current, displayed/available, and the scope matches what is actually being conducted (no training outside approved scope).",
       th="ใบรับรอง ATO (FTO-0007) และการอนุมัติหลักสูตรเป็นปัจจุบัน พร้อมแสดง และขอบเขตตรงกับการฝึกที่ทำจริง (ไม่มีการฝึกนอกขอบเขต)",
       rk="ORA.GEN.125", mt=["DOC","XCK"],
       how="Sight certificate + approval schedule. Compare course list vs students actually enrolled/courses marketed. Any activity outside scope = major finding.",
       ref="ATO certificate / approval schedule"),
  dict(d="Changes requiring prior approval (key personnel, facilities, courses, aircraft) were applied for and approved BEFORE implementation; non-prior-approval changes notified as required.",
       th="การเปลี่ยนแปลงที่ต้องขออนุมัติก่อน (บุคลากรหลัก สถานที่ หลักสูตร อากาศยาน) ได้ยื่นและได้รับอนุมัติก่อนดำเนินการจริง และการเปลี่ยนแปลงอื่นแจ้งตามกำหนด",
       rk="ORA.GEN.130", mt=["DOC","XCK"],
       how="List changes in last 24 months (from minutes/records). For each: CAAT application/approval date vs implementation date. เทียบ MOC-001/002/003 records",
       ref="OMM / MOC forms, CAAT correspondence"),
  dict(d="Conditions for continued validity are being met: fees paid, access granted, certificate not surrendered/revoked; previous CAAT findings closed within agreed dates.",
       th="เงื่อนไขการคงอยู่ของใบรับรองครบ: ชำระค่าธรรมเนียม ให้การเข้าตรวจ และข้อบกพร่องจากการตรวจของ กพท. ครั้งก่อนปิดตามกำหนด",
       rk="ORA.GEN.135", mt=["DOC"],
       how="Sight fee receipts, last CAAT inspection report and closure evidence of its findings (cross-ref Findings_PageRef_12JUN2026).",
       ref="CAAT correspondence / CAPA log"),
 ]),
]),
]
